[package]
name = "hyprland_dyn_workspaces"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Michał Moczulski"]
description = "Insert a new workspace after active."

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
hyprland = "0.4.0-beta.2"
anyhow = "1.0.98"